# Understanding TensorFlow APIs

In [2]:
import tensorflow as tf

2025-09-12 10:20:49.613962: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## tf.meshgrid

* `tf.meshgrid` is a tool that takes two 1D rulers (one for your x-axis, one for your y-axis) and uses them to create a full 2D coordinate system.



In [4]:
grid_size = 2
## here we are creating a ruler with values [0., 1.] for both x and y
coorinate_range = tf.range(grid_size, dtype=tf.float32)
grid_X,grid_Y = tf.meshgrid(coorinate_range,coorinate_range)
grid_X,grid_Y

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0., 1.],
        [0., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [1., 1.]], dtype=float32)>)

* Since both our x and y rules have 2 coordinate points, we'll have total of 4 coordinate points in our 2D coordinate system
* The first output, `grid_X`, tells you the x-coordinate for every point in the 2D grid. So row 0 and 0. and 1. and row 1 has same coordinate points
* The second output, `grid_Y`, tells you the y-coordinate for every point. 
* This makes more sense when you combine them into single tensor to give us a tensor with all the grid corners


In [6]:
grid = tf.stack(values=[grid_X,grid_Y], axis=2)
grid

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [1., 0.]],

       [[0., 1.],
        [1., 1.]]], dtype=float32)>

* Now grid is a tensor of shape (2,2,2) which gives us all the coorinates in our 2D grid based on our rules
* First point is 0,0 then going right we get 1,0, then top left corner would be 0,1 and top right would be 1,1